Задание: отрисуй меня полностью (парт1)
htmlacademy-javascript/1733897-kekstagram-25 pull request #5
Opened 2022-03-16 10:14 UTC by AleksandrNovikov88

2022-03-16 21:08 UTC, PolinaShneider commented on js/main.js
>  import {createPhoto} from './data.js';
Смотри, вижу несколько проблем. Первое — у тебя неправильный путь до js-файла в index.html. Если ты запустишь проект и откроешь в браузере, ты увидишь 404

Нужно путь поправить
<img width="439" alt="image" src="https://user-images.githubusercontent.com/15448200/158691206-b0e428c7-5cfd-4344-b1be-1225b85d0d87.png">

2022-03-16 21:12 UTC, PolinaShneider commented on js/main.js
>  import {stringLength} from './util.js';
Во-вторых, у тебя внутри каждого createPhoto генерируется айдишник. В файле data.js ты в цикле генерируешь 25 фото. Возможных айдишников столько же: от 1 до 25. Как только ты пытаешься 26-ой и 27-ой раз вызвать функцию генерации фото, свободных айдишников больше нет, JavaScript все равно пытается сгенерировать нечто уникальное и уходит в бесконечный цикл.

Возможное решение: почистить лишние вызовы createPhoto, и вообще main.js тоже можно почистить от старого кода

<img width="298" alt="image" src="https://user-images.githubusercontent.com/15448200/158691847-47d81ff5-1e3f-415d-a847-b032cf9a3ba7.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/15448200/158691860-6b958441-b218-4724-88dc-8d035f340990.png">

2022-03-16 21:14 UTC, PolinaShneider commented on js/thumbnails.js
> +const createPhotos = createPhoto();
Дальше: createPhoto() у тебя возвращает объект, а не массив. На нем тебе не вызвать forEach. Возможное решение — закинуть сюда то что мы удалим из data.js. Вызвать эту функцию в цикле, результаты вызова сохранить в массив, и forEach уже пройтись по массиву, как ты и делаешь

2022-03-16 21:14 UTC, PolinaShneider commented on js/thumbnails.js
> +  pictureElement.querySelector('.picture__img').textContent = photo.url;
Здесь у тебя должна быть подстановка в src, а не в textContent

2022-03-16 21:16 UTC, PolinaShneider commented on js/thumbnails.js
> +const picturesContainer = document.querySelector('.pictures');
Теперь поехали по критериям. 

Стиль именования переменных сохраняется во всех модулях, например:

- если переменные, которые хранят DOM-элемент, содержат слово Element или любое другое, но одно и то же везде.

https://up.htmlacademy.ru/javascript/25/criteries#d6

2022-03-16 21:18 UTC, PolinaShneider commented on js/thumbnails.js
> +
Удали, пожалуйста, этот коммент. Он уже не актуален
<img width="558" alt="image" src="https://user-images.githubusercontent.com/15448200/158692657-5eb552b3-1bec-4c0d-b98e-b84c961b2d1a.png">

2022-03-16 21:20 UTC, PolinaShneider commented on js/main.js
>  import {stringLength} from './util.js';
И кстати 25 выглядит как «магическое число»: https://up.htmlacademy.ru/javascript/25/criteries#d19

Давай её в константу (критерии [Б7](https://up.htmlacademy.ru/javascript/25/criteries#b7) и [Б10](https://up.htmlacademy.ru/javascript/25/criteries#b10))

2022-03-16 21:21 UTC, PolinaShneider requested changes
Нужно кое-что поправить

2022-03-17 05:10 UTC, AleksandrNovikov88 commented on js/thumbnails.js
> +  pictureElement.querySelector('.picture__img').textContent = photo.url;
Т.е. просто вместо textContent я пишу src и всё? Где то я читал в материалах про управление src...

2022-03-17 09:23 UTC, merged