Что то я сделал, не знаю что
htmlacademy-javascript/1733897-kekstagram-25 pull request #6
Opened 2022-03-24 10:47 UTC by AleksandrNovikov88

2022-03-24 19:16 UTC, PolinaShneider commented on js/user-form.js
> +import { isEscapeKey, stringLength } from './util.js';
У тебя фейлится проверка линтера в реквесте, надо с этим разобраться
<img width="627" alt="image" src="https://user-images.githubusercontent.com/15448200/159993417-a2c4996e-56bc-4634-b4ab-d38594f13b11.png">

2022-03-24 19:24 UTC, PolinaShneider commented on js/user-form.js
> +    return false;
Можно записать проще: https://up.htmlacademy.ru/javascript/25/criteries#d18

2022-03-24 19:24 UTC, PolinaShneider commented on js/user-form.js
> +  const hashtags = string.split(' ').filter((item) => item !== '');
Можно записать: `.filter(Boolean)`, так как пустая строка false в логическом контексте

2022-03-24 19:25 UTC, PolinaShneider commented on js/user-form.js
> +const checkUniq = (string) => {
checkUnique — опечатка

2022-03-24 19:25 UTC, PolinaShneider commented on js/user-form.js
> +  const allUnique = !hashtags.some((item, index) => hashtags.indexOf(item) < index);
Можно заинлайнить и сразу вернуть значение
```
return allUnique = !hashtags.some((item, index) => hashtags.indexOf(item) < index);
```

2022-03-24 19:27 UTC, PolinaShneider commented on js/user-form.js
> +const checkHashtag = (string) => string.split(' ').filter((item) => item !== '').every((item) => item[0] === '#');
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

2022-03-24 19:31 UTC, PolinaShneider commented on js/user-form.js
> +const checkMaxLength = (string) => string.split(' ').filter((item) => item !== '').every((item) => checkLength(item, MAXLENGTH_HASHTAGS_SYMBOLS));
Зачем тебе промежуточная фильтрация?  Можешь объяснить? :)
Формально ноль символов (пустая строка) меньше MAXLENGTH_HASHTAGS_SYMBOLS, и это ок

2022-03-24 19:39 UTC, PolinaShneider commented on js/user-form.js
> +  evt.preventDefault();
Про нейминг забыл: https://up.htmlacademy.ru/javascript/25/criteries#d6

2022-03-24 19:40 UTC, PolinaShneider commented on js/user-form.js
> +  classTo:'text__hashtags',
Пробел после двоеточия пропустил

2022-03-24 19:42 UTC, PolinaShneider commented on js/user-form.js
> +  const allUnique = !hashtags.some((item, index) => hashtags.indexOf(item) < index);
А вообще давай проверять уникальность через [Set](https://learn.javascript.ru/map-set#set)
```
return hashtags.length === new Set(hashtags).size;
```

2022-03-24 19:43 UTC, PolinaShneider commented on js/user-form.js
> +const form = document.querySelector('.img-upload__form');
Про нейминг забыл: https://up.htmlacademy.ru/javascript/25/criteries#d6

2022-03-24 19:44 UTC, PolinaShneider commented on js/user-form.js
> +  evt.preventDefault();
Самое главное: у тебя форма из-за этой строчки `evt.preventDefault()` вообще не отправляется никогда, даже если она валидна.

Тебе нужно таким образом запрещать отправку формы ТОЛЬКО если с данными что-то не то)

2022-03-24 19:48 UTC, PolinaShneider commented on js/user-form.js
> +    hashtag.style.background = 'pink';
У тебя при валидации просто поле окрашивается в красный цвет, и никакого сообщения пользователю не выводится.

Вероятно, как-то не так у тебя активируются валидации pristine, либо, возможно, это из-за преждевременного preventDefault
<img width="559" alt="image" src="https://user-images.githubusercontent.com/15448200/159997734-ee13c74f-e8e5-4eeb-a404-1c33374d2ebd.png">

2022-03-24 19:52 UTC, PolinaShneider requested changes
В целом неплохо, но нужно доработать. Основная рекомендация: потестируй свой интерфейс в браузере.

Если форма валидная, она должна отправляться, если нет — должны показываться соответствующие сообщения об ошибках

2022-03-27 20:27 UTC, AleksandrNovikov88 commented on js/user-form.js
> +    return false;
Пытался проще, но ломается всё, перестает работать.

2022-03-27 20:28 UTC, AleksandrNovikov88 commented on js/user-form.js
> +  const hashtags = string.split(' ').filter((item) => item !== '');
Сделал.

2022-03-27 20:28 UTC, AleksandrNovikov88 commented on js/user-form.js
> +const checkUniq = (string) => {
+

2022-03-27 20:29 UTC, AleksandrNovikov88 commented on js/user-form.js
> +  const allUnique = !hashtags.some((item, index) => hashtags.indexOf(item) < index);
Не понятно.

2022-03-27 20:30 UTC, AleksandrNovikov88 commented on js/user-form.js
> +const checkHashtag = (string) => string.split(' ').filter((item) => item !== '').every((item) => item[0] === '#');
Тоже не понял. Дело в том что этот кусок скопировал с того репозитория, понял что он делает вцелом.

2022-03-27 20:31 UTC, AleksandrNovikov88 commented on js/user-form.js
> +const checkMaxLength = (string) => string.split(' ').filter((item) => item !== '').every((item) => checkLength(item, MAXLENGTH_HASHTAGS_SYMBOLS));
Тоже не понял что можно убрать тут.

2022-03-27 20:31 UTC, AleksandrNovikov88 commented on js/user-form.js
> +const form = document.querySelector('.img-upload__form');
Сделал.

2022-03-27 20:31 UTC, AleksandrNovikov88 commented on js/user-form.js
> +  evt.preventDefault();
Сделал.

2022-03-27 20:33 UTC, AleksandrNovikov88 commented on js/user-form.js
> +    hashtag.style.background = 'pink';
![image](https://user-images.githubusercontent.com/79405897/160299833-f60b7c65-96ec-46bb-baab-a29fb3a3045f.png)
сделал вот так. теперь показывает внизу

2022-03-28 20:33 UTC, PolinaShneider commented on js/user-form.js
> +    return false;
Напиши просто `return hashtags.length <= HASGTAGS_COUNTS`

2022-03-28 20:36 UTC, PolinaShneider commented on js/user-form.js
> +  const allUnique = !hashtags.some((item, index) => hashtags.indexOf(item) < index);
Смотри, ты проверяешь, что у тебя только уникальные значения среди хэштегов.

Set — структура данных, в которой не поддерживаются дубликаты. То есть, если у тебя в Set было `[1,2,3,4]`, и ты долбавляешь 2, то так и останется `[1,2,3,4]`, потому что 2 уже есть, а дубликаты запрещены.

Самый простой способ проверить на наличие дубликатов — создать Set на основе массива. Если он по размеру такой же, как массив, значит, в массиве дубликатов нет. Потому что, попадая в Set, дубликаты "растворяются"

2022-03-28 20:38 UTC, PolinaShneider commented on js/user-form.js
> +const checkHashtag = (string) => string.split(' ').filter((item) => item !== '').every((item) => item[0] === '#');
Ты проверяешь, что у тебя строка начинается с хэштега при помощи `item[0] === '#'`. Это можно сделать при помощи `item.startsWith('#')`

2022-03-28 20:43 UTC, merged